name = "ry7yy-telegram-bot"
main = "worker.js"
compatibility_date = "2025-09-30"

[vars]
# ğŸ”‘ Ø¶Ø¹ ØªÙˆÙƒÙ† Ø§Ù„Ø¨ÙˆØª Ù‡Ù†Ø§ (Ø£Ùˆ Ø®Ø²Ù‘Ù†Ù‡ ÙƒØ³ÙØ± ÙÙŠ Cloudflare dashboard)
#env.BOT_TOKEN
CHANNEL_USERNAME = "RY7DY"   # Ø¨Ø¯ÙˆÙ† @

[[kv_namespaces]]
binding = "SESSION_KV"
id = "3a1ae8dadcf04ece8ac977e870b242e5"